name: Run Calculation, Deploy and Commit.

# For TESTING, REMEMBER to adjust expiration of tx in 
# mstx.js :: main() :: proposeInput.trx.expiration
# on:
#   push:
#     branches:
#       - slack-test
on:
  schedule:
    - cron: '05 * * * *'
    # run this every fifteen minutes, every hour of every day

# Official run time. DO NOT CHANGE
# https://crontab.guru/#00_11_*_*_5
# “At 11:00 on Friday.”
# on:
#   schedule:
#     - cron: '00 11 * * 5'

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Insall dependencies
      - run: npm ci

      # Banner
      - run: node index.js --help
      # Retrieve data and calculate fees
      - run: node index.js --ckey ${{ secrets.COVALENT_API_KEY }}

      # Build multi-sig tx
      - run: node mstx.js -p ${{ secrets.PRIVATE_KEY_PANCAKE }} -b ${{ secrets.SLACK_BOT_TOKEN_XOXB }} -s ${{ secrets.SLACK_SIGNING_SECRET }} -a ${{ secrets.SLACK_APP_TOKEN_XAPP }}

      # # copy and commit this weeks fees, not sure if this makes sense. I think we can remove this.
      # - run: cp dist/index.json "data/$(date).json"
      # - uses: EndBug/add-and-commit@v8
      #   with:
      #     add: '*.json --force'
      #     cwd: './data/'
      #     message: 'Commit Calculations'

  # deploy:
  #   needs: calculation
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: deploy
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist


  # Post notification to slack
  # slackNotification:
  #   needs: deploy
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Slack Notification
  #     uses: rtCamp/action-slack-notify@v2
  #     env:
  #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #       SLACK_USERNAME: PCS_Bot
  #       SLACK_ICON: https://effect.network/img/logo/logo_icon.png
  #       SLACK_MESSAGE: 'Updated Pancake Swap Fee Page: https://effectai.github.io/dao-pancake-fees/ :rocket:'

